# integrate

In [ ]:
import scipy.integrate as integrate

In [2]:
def f(x,y):
    return x+y
integrate.dblquad(f,0,1,lambda x:0,lambda x:2)

(3.0, 4.436070580899685e-14)

In [3]:
from scipy.integrate import quad

In [4]:
def integradefun(x):
    return x

In [5]:
quad(integradefun,0,1)

(0.5, 5.551115123125783e-15)

In [6]:
def integ(x,a,b):
    return x*a+b

In [7]:
a=3
b=2

In [8]:
quad(integ,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

# Optimization

In [9]:
import numpy as np
from scipy import optimize

In [10]:
def f(x):
    return x**2+5*np.sin(x)

In [12]:
minimaval=optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


# linear algebra

In [13]:
import numpy as np
from scipy import linalg
a = np.array([[5, 2], [2, 3]])
b = np.array([18, 5])
x = np.linalg.solve(a, b)
x

array([ 4., -1.])

In [14]:
matrix=np.array([[10,6],[2,7]])

In [15]:
matrix

array([[10,  6],
       [ 2,  7]])

In [16]:
type(matrix)

numpy.ndarray

In [17]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [18]:
linalg.det(matrix)

58.0

In [22]:
array1=np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [23]:
array2=np.array([21,9,6])

In [24]:
linalg.solve(array1,array2)

array([ 4.95,  4.35, -1.95])

In [26]:
arraysv=np.array([[3,5,1],[9,5,7]])

In [27]:
arraysv.shape

(2, 3)

In [28]:
linalg.svd(arraysv)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [29]:
from scipy.stats import norm

In [30]:
norm.rvs(loc=0,scale=1,size=10)#loc is mean and scale is std dev

array([-2.38346299,  2.60204698,  1.12802117,  0.72324673,  0.32086435,
        0.25524768, -1.16370396, -0.56196282,  0.66654966, -0.47638286])

In [36]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [33]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18