# creating and printing array

In [1]:
import numpy as np

In [2]:
first_numpy_array=np.array([1,2,3,4])

In [3]:
first_numpy_array

array([1, 2, 3, 4])

In [4]:
zero_array=np.zeros((2,2))

In [5]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [6]:
ones_array=np.ones((4,4))

In [7]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
empty_array=np.empty((3,3))

In [9]:
empty_array

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 5.277e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [10]:
np_arrange=np.arange(12)

In [11]:
np_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
print(np_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
np_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np_linespace=np.linspace(1,3,6)

In [15]:
print(np_linespace)

[1.  1.4 1.8 2.2 2.6 3. ]


In [16]:
oned=np.arange(15)

In [17]:
print(oned)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
twod=oned.reshape(3,5)

In [19]:
print(twod)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
twod=oned.reshape(5,3)

In [21]:
twod

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
print(twod)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [23]:
threed=np.arange(27).reshape(3,3,3)

In [24]:
print(threed)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


# Basic operations

In [25]:
np.add(50,100)

150

In [26]:
np.subtract(100,50)

50

In [27]:
hours_worked=np.array([10,5,6,3])

In [28]:
hours_worked

array([10,  5,  6,  3])

In [29]:
sum(hours_worked)

24

In [30]:
for_5_days=hours_worked*5

In [31]:
for_5_days

array([50, 25, 30, 15])

In [32]:
sum(for_5_days)

120

In [33]:
for_5_days[for_5_days>25]

array([50, 30])

In [34]:
np.logical_and(for_5_days>20,for_5_days<50)

array([False,  True,  True, False])

# Access array

In [35]:
cyclist_trials=np.array([[10,15,17,26],[12,11,21,24]])

In [36]:
print(cyclist_trials)

[[10 15 17 26]
 [12 11 21 24]]


In [37]:
cyclist_trials[0]

array([10, 15, 17, 26])

In [38]:
cyclist_trials[1]

array([12, 11, 21, 24])

In [39]:
cyclist_trials[0][0]

10

In [40]:
cyclist_trials[1][2]

21

In [41]:
cyclist_trials[:,3]

array([26, 24])

In [42]:
cyclist_trials.shape

(2, 4)

In [43]:
cyclist_trials[:,0:2]

array([[10, 15],
       [12, 11]])

In [44]:
for i in cyclist_trials:
    print(i)



[10 15 17 26]
[12 11 21 24]


In [45]:
test_scores=np.array([[55,75,65,95],[25,45,85,96]])

In [46]:
pass_score=test_scores>60

In [47]:
pass_score

array([[False,  True,  True,  True],
       [False, False,  True,  True]])

In [48]:
test_scores[pass_score]

array([75, 65, 95, 85, 96])

In [49]:
abc=np.array(['Mumbai','Indore','Goa','Himachal'])

In [51]:
abcview=abc.view()

In [52]:
abc

array(['Mumbai', 'Indore', 'Goa', 'Himachal'], dtype='<U8')

In [53]:
len(abcview)

4

In [54]:
abcview[3]='Shimla'

In [55]:
abcview

array(['Mumbai', 'Indore', 'Goa', 'Shimla'], dtype='<U8')

In [56]:
abc

array(['Mumbai', 'Indore', 'Goa', 'Shimla'], dtype='<U8')

In [59]:
np.sqrt([10,5,6])

array([3.16227766, 2.23606798, 2.44948974])

In [60]:
np.cos(0)

1.0

In [61]:
np.floor([1.86,2.4])

array([1., 2.])

In [62]:
np.ceil([5.8,1.2])

array([6., 2.])

In [63]:
np.exp(5)

148.4131591025766